[book]
authors = ["Gijs Arkink"]
language = "en"
multilingual = false
src = "src"
title = "Proces and safety Induvidual 506101"

[preprocessor.plantuml]
plantuml-cmd="http://localhost:8080"

[output.html]
defaulth-theme = "Ayu"